### ISSUE TITLE
opening files?

### ISSUE THREAD

**Issue by Ninjistix** [ReignOfComputer/RoCs-PC#1]
tried to open files with pkhex, and was unable too, is there something else I should be using?

**Comment by ReignOfComputer** [comment]
Which generation Pokemon are you attempting to open?

**Comment by Ninjistix** [comment]
actually looks like just gen I and II, they seem to have no file type

**Comment by ReignOfComputer** [comment]
For the latest version of PKHeX, use the "Rhydon" folder for Gen 1. You can't open the .pk1 files directly, but you can open my save data in the "Save Data" folder, from what I see.

For Gen 2, it appears that PKHeX has a different structure for Pokemon files (pk2). While I don't have them in that format, you can still view the Pokemon by opening the save data.

**Comment by Ninjistix** [comment]
okay seems i can open the saves with PKHeX and Dump the boxes, to the current .pk1/pk2 versions, would you like me to dump them for you?

**Comment by ReignOfComputer** [comment]
The .pk1 are all done, it's just the .pk2. If you'd like to help with that I'd be super grateful, thanks :)

**Comment by Ninjistix** [comment]
okay ill attach it here, dumping it now

**Comment by ReignOfComputer** [comment]
If the Pokemon isn't in the save file, you can load it into the save using PKXDelta or other Gen 2 editor first.

**Comment by Ninjistix** [comment]
[RoC Gen2 - Crystal.zip](https://github.com/ReignOfComputer/RoCs-PC/files/518959/RoC.Gen2.-.Crystal.zip)
[RoC Gen2 - Gold.zip](https://github.com/ReignOfComputer/RoCs-PC/files/518958/RoC.Gen2.-.Gold.zip)
[RoC Gen2- Silver.zip](https://github.com/ReignOfComputer/RoCs-PC/files/518957/RoC.Gen2-.Silver.zip)
dumped the boxes from the sav files

**Comment by ReignOfComputer** [comment]
Thanks, I'll sort this out later.

**Comment by Ninjistix** [comment]
i wanted to find a way to batch convert the gen2 files into .pk2 but i can't find any program that lets me open them in batches.. don't want to go over all of the files 1 by 1, i did the dumps from the actual saves above using PKHeX, so by default they are all .pk2, also renamed the folders in #2 so they can be viewed easier on github

**Comment by Ninjistix** [comment]
hey @ReignOfComputer / @invalid-email-address check my PR that i opened, I had fixed slowbro/slowpoke and also renamed some folders to make them more git friendly. also started to convert get 2 sav's to .pk2

**Comment by ReignOfComputer** [comment]
It's a little bit of a mess because of your large commits, so I've ended up grabbing directly from your commit and adding the Unowns. Thanks for helping out.

**Comment by Ninjistix** [comment]
no problem, and the commits were large cuz i added a 0 to the folder numbering system you had, so it would be better organized on the git page listing, eg, 01,02,03,-,09,10,11 etc

**Comment by ReignOfComputer** [comment]
Oh, thanks for the suggestion. I've got a few things relying on the current structure (I'm just lazy to edit those), once I eventually complete 5/6th Gen a little more I'll apply your numbering :)

**Comment by Ninjistix** [comment]
oh okay... and i just started playing from GEN1 so if i find anything missing ill commit it here to help out
