### ISSUE TITLE
Beautifly has a issue

### ISSUE THREAD

**Issue by Tobyheiam** [ReignOfComputer/RoCs-PC#10]
<img width="598" alt="screen shot 2017-04-30 at 11 58 20 am" src="https://cloud.githubusercontent.com/assets/22422919/25565813/b6995462-2d9c-11e7-806c-c15785494136.png">
I don't know if it is a BUG of PKHeX.

**Comment by ReignOfComputer** [comment]
Not sure either. The Pokemon aren't edited, unless something screwed up during the dumping process.

For @Kaphotics to comment please. You may need to open an issue on PKHeX's end.

**Comment by Tobyheiam** [comment]
it shows legal while I'm using PKMN-NTR (PKHeX.Core: Updated to 20170318), but after dragging the pkm to the latest build of PKHeX, it becomes illegal. So i guess its a bug of PKHeX.  @kwsch

**Comment by kwsch** [comment]
https://github.com/kwsch/PKHeX/commit/24b55b7b79afba85d0c9f0db8ecef3f12a7cd7b3
>fix wurmple ECPID comparison (only continue if ALL are wurmple)
