### ISSUE TITLE
Problems withs any files in sword and shield

### ISSUE THREAD

**Issue by Alda1980** [ReignOfComputer/RoCs-PC#11]
sorry for bothering you reign, I want to give you a feed, so that you have in mind that some files give error in the pkhex, so that you see the fault that gives you I attached the error that gives by gyazo.

I have noticed that the files with error have a base size of 344kb, it may be due to the file compression mode.

https://gyazo.com/b94e4589a022c60b13e84e6034ad09c9

Attentive greetings alda1980 from Spain.

**Comment by ReignOfComputer** [comment]
Both file sizes open correctly on the latest release of PKHeX. Can you make sure you're on the latest version (191115e)?

**Comment by Alda1980** [comment]
ops sorry I'll see if the version is on my laptop, if I don't download it, but first of all thank you and sorry for the inconvenience. I wanted to help but I'm sorry.
