### ISSUE TITLE
 Shiny egg pkm from Gen2 Daycare man

### ISSUE THREAD

**Issue by Ninjistix** [ReignOfComputer/RoCs-PC#3]
ignore this first post, the unknown problems is with PKHeX

**Comment by Ninjistix** [comment]
hey @ReignOfComputer here's the 7 Shiny egg pkm from Gen2 Daycare man

[Shiny Daycare Eggs.zip](https://github.com/ReignOfComputer/RoCs-PC/files/542535/Shiny.Daycare.Eggs.zip)

**Comment by ReignOfComputer** [comment]
Thanks @Ninjistix. Added in.
