### ISSUE TITLE
MISSING NO. 163  IN 24 - Gen VII - SM Collection

### ISSUE THREAD

**Issue by Tobyheiam** [ReignOfComputer/RoCs-PC#6]
MISSING NO. 163  IN 24 - Gen VII - SM Collection

**Comment by ReignOfComputer** [comment]
Hoothoot? You can't catch that in SuMo.

**Comment by Tobyheiam** [comment]
But I can't find it in  sm collection / Pokébank/ . Total Pokémon are 800( bank + smpokemon).

**Comment by ReignOfComputer** [comment]
I'll look into this later. Thanks.

**Comment by ReignOfComputer** [comment]
Thanks for spotting. Forgot to add that in when I caught it in X.
