### ISSUE TITLE
File Names Too Long

### ISSUE THREAD

**Issue by kamronbatman** [ReignOfComputer/RoCs-PC#7]
Hi RoC!

Please rename your files and/or folders so they aren't breaking my computer.  <3

**Comment by ReignOfComputer** [comment]
Ahhhh I don't know how or where to start! I'm facing problems myself ;(

Extract it to root for the time being? >.<

**Comment by kamronbatman** [comment]
I did.  I am writing a file renamer, so we can use that when it is finished.

**Comment by ReignOfComputer** [comment]
I can't wait ;)
